require 'json'
require 'fileutils'

# Make sure this matches the asset_cdn bucket name in _config.yml
ASSET_BUCKET = "nateware-blog"

desc "Generate JavaScript file with background images array"
task :backgrounds do
  puts "Generating background images JavaScript..."

  backgrounds_dir = File.join(Dir.pwd, 'assets', 'backgrounds')

  # Return early if backgrounds directory doesn't exist
  unless File.directory?(backgrounds_dir)
    warn "Warning: Directory not found: #{backgrounds_dir}"
  end

  # Scan for JPEG files
  image_files = Dir.glob(File.join(backgrounds_dir, '*.jp*g'))
                    .map { |f| "/assets/backgrounds/#{File.basename(f)}" }
                    .sort

  if image_files.empty?
    warn "Warning: No JPEG files found in #{backgrounds_dir}"
  end

  # Generate JavaScript content with array
  js_content = "// Auto-generated by Jekyll background_images plugin\n"
  js_content += "// Generated at: #{Time.now}\n"
  js_content += "// Total images: #{image_files.length}\n"
  js_content += "var BACKGROUND_IMAGES = #{image_files.to_json};\n"

  # Write to assets/js/backgrounds.js
  output_dir = File.join(Dir.pwd, 'assets', 'js')
  FileUtils.mkdir_p(output_dir)
  output_file = File.join(output_dir, 'backgrounds.js')
  File.write(output_file, js_content)

  puts "Backgrounds: Generated #{output_file} with #{image_files.length} images"
  puts "*** Don't forget to run `rake sync_assets` to upload assets to the CDN! ***"
end

desc "Sync assets to Google Cloud Storage bucket"
task :sync_assets do
  local_dir = File.join(Dir.pwd, 'assets')

  puts "Syncing assets to Google Cloud Storage bucket: #{ASSET_BUCKET}"
  puts "Local directory: #{local_dir}"

  # Run gsutil rsync command
  command = "gcloud storage rsync #{local_dir} gs://#{ASSET_BUCKET}/assets --recursive"
  puts "Running command: #{command}"
  system(command) || abort("Error: Failed to sync assets to GCS bucket.")
end